version: 2.0.{build}
image: Visual Studio 2022

configuration: Release

init:
- ps: $env:nuget_ver=$env:appveyor_build_version
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(nuget_ver)
  assembly_file_version: $(nuget_ver)
  assembly_informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  nuget restore src\DotJEM.Web.Host.sln

build:
  project: src\DotJEM.Web.Host.sln
  publish_nuget: true

on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot

deploy:
  - provider: NuGet
    name: Master
    api_key:
      secure: bFNGQmfzcl8+qMzGRyjuppyao5/sQlK4w3ikBuYi4qQTniVxdfoyWImJwHHktQm0
    on:
      branch: master 
      
  - provider: NuGet
    name: Beta
    api_key:
      secure: bFNGQmfzcl8+qMzGRyjuppyao5/sQlK4w3ikBuYi4qQTniVxdfoyWImJwHHktQm0
    on:
      branch: beta  
      
  - provider: NuGet
    name: Nsw
    api_key:
      secure: bFNGQmfzcl8+qMzGRyjuppyao5/sQlK4w3ikBuYi4qQTniVxdfoyWImJwHHktQm0
    on:
      branch: nsw 
